# Generated by Django 4.1.6 on 2023-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderdetails',
            name='Pcs_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorderdetails',
            name='pcs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorderdetails',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplierstockdetails',
            name='Pcs_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
