# Generated by Django 4.1.6 on 2023-06-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_supplierorderdetails_pcs_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3)),
                ('pcs', models.IntegerField(blank=True, default=0, null=True)),
                ('Buy_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('Sale_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('Profit', models.IntegerField(blank=True, default=0, null=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.products')),
                ('Supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
            ],
        ),
    ]
