# Generated by Django 4.1.6 on 2023-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customer_custorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstockdetails',
            name='In_Stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
